import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next and must not be hand-edited.
    // .claude/** holds Claude Code's internal worktrees (each a full nested
    // checkout with its own .next) — never lint those, or `pnpm lint` floods
    // with thousands of false positives from the nested build artifacts.
    ignores: [".next/**", "node_modules/**", "coverage/**", "out/**", "next-env.d.ts", ".claude/**"],
  },
  {
    // M33 / D-089: intentional rest-sibling discards (`{ foo: _foo, ...rest }`)
    // are not unused-var noise — ignoreRestSiblings matches the TypeScript
    // eslint recommendation for that pattern (resonance.ts summary strip).
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
    },
  },
  {
    // C-7: "The UI never imports providers." Pages get provider metadata
    // via module actions (e.g. listProviderOptions); components take the
    // literal-union types from @/core/runner.
    files: ["src/app/**/*.{ts,tsx}", "src/components/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/providers", "@/providers/*", "@/providers/**"],
              message:
                "C-7: the UI never imports providers — use a module action for metadata and @/core/runner for ProviderId/GenerationMode types.",
            },
          ],
        },
      ],
    },
  },
];

export default eslintConfig;
